#!/bin/bash
set -eu

rm -rf build

mkdir build

COMMIT_HASH=`git rev-parse --short HEAD`



node_modules/.bin/elm make ./src/Main.elm --optimize --output=build/elm.js 
node_modules/.bin/terser build/elm.js  --no-rename --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters=true,keep_fargs=false,unsafe_comps=true,unsafe=true,passes=2' --mangle --output=build/elm.js 

cp docs/index.html                  build/200.html
cp docs/favicon.ico                 build/
cp docs/robots.txt                  build/
cp docs/_redirects                  build/
cp docs/sitemap.txt                 build/
cp docs/0.json                      build/
cp docs/1.json                      build/
cp docs/3.json                      build/
cp docs/6.json                      build/
cp docs/10.json                     build/
cp docs/CNAME                       build/
cp docs/google314fa0e42afdf9a1.html build/

node_modules/.bin/replace '_COMMIT_' $COMMIT_HASH build/200.html -m -i
